# Generated by Django 2.0.2 on 2018-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.DateField(blank=True),
        ),
    ]
