# Generated by Django 2.0.2 on 2018-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0002_auto_20180206_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
