# Generated by Django 2.0.2 on 2018-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0004_auto_20180207_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('PAPER', 'paper'), ('BOOK', 'book'), ('AUD', 'audio'), ('VID', 'video'), ('POST', 'post'), ('ART', 'artwork')], db_index=True, default='PAPER', max_length=5),
        ),
    ]
